# Generated by Django 2.1.7 on 2019-03-24 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190321_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('sheet_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='musicfavourite',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='music.MusicList'),
        ),
        migrations.AlterField(
            model_name='musicfavourite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musichistory',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='music.MusicList'),
        ),
        migrations.AlterField(
            model_name='musichistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
