# Generated by Django 2.1.7 on 2019-03-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190324_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicfavourite',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='musicfavourite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='musichistory',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='musichistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
