# Generated by Django 2.1.7 on 2019-03-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190324_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musichistory',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='music.MusicList', unique=True),
        ),
    ]
