# Generated by Django 2.1.7 on 2019-03-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190325_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
