# Generated by Django 2.1.7 on 2019-03-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_singer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
