# Generated by Django 2.1.7 on 2019-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190320_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
                ('singer_id', models.IntegerField()),
                ('like', models.IntegerField(default=0)),
                ('search', models.IntegerField(default=0)),
                ('play', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
            ],
        ),
    ]
