# Generated by Django 2.1.7 on 2019-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userlike'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlike',
            table='user_like',
        ),
    ]
