# Generated by Django 2.1.7 on 2019-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFavourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('Fmusic_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_favourite',
            },
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_path', models.CharField(max_length=100)),
                ('lrc_path', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=15)),
                ('length_time', models.CharField(max_length=5)),
                ('music_pic', models.CharField(max_length=100)),
                ('play_No', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'music_list',
                'ordering': ['list_id'],
            },
        ),
        migrations.CreateModel(
            name='MusicSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
            ],
            options={
                'db_table': 'music_sheet',
            },
        ),
        migrations.CreateModel(
            name='UserSheet',
            fields=[
                ('sheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('sheet_num', models.IntegerField(default=0)),
                ('sheet_pic', models.CharField(default='/images/upload/sheet_pic/default.png', max_length=100)),
            ],
            options={
                'db_table': 'user_sheet',
            },
        ),
    ]
