# Generated by Django 2.1.7 on 2019-03-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('music_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_history',
            },
        ),
        migrations.DeleteModel(
            name='MusicSheet',
        ),
        migrations.DeleteModel(
            name='UserSheet',
        ),
        migrations.RenameField(
            model_name='musicfavourite',
            old_name='Fmusic_id',
            new_name='music_id',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='play_No',
        ),
    ]
